language: go

go:
  - "1.16.x"

install: true

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.40.1

script:
  - golangci-lint run --modules-download-mode=vendor





