name: golang-ci

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:v1.58
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: remove git
        run: rm -rf .git
      - name: golangci-lint
        run: golangci-lint run
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: build
        run: go build -o autotest ./
